Enable_Wandb: True   # default: True
##### train
exp_name: mnist_256x4x0_finddim
output_folder: exps/exp_finddim
dataset: mnist
batch_size: 512
num_epochs: 500       # number of epochs (default: 100)

seed: 42              # seed for everything
lr: 3e-4
num_workers: 16

# loss
calc_sim_loss: Ture
sim_loss: 0             # 权重为0,则表示不参与训练; 仅 calc_sim_loss=True & sim_loss > 0时参与训练
commitment_cost: 0.25   # hyperparameter for the commitment loss (default: 0.25)

# model
# Latent space
hidden_size: 128        # size of the latent vectors (default: 128)
num_residual_hidden: 32 # size of the redisual layers (default: 32)
num_residual_layers: 2  # number of residual layers (default: 2)

# codebook
# Quantiser parameters
shuffle_scale: 0      # scale factor for upsample and downsample the feature vectors
num_embedding: 256      # number of codebook (default: 512)
dim_embedding: 4
# size_dmbedding: num_embedding * dim_embedding

distance: cos           # distance for codevectors and features
split_type: fixed       # fixed, interval, random
anchor: closest         # anchor sampling methods (random, closest, probrandom)

##### eval
num_test: 0  # how many examples to load for testing (default: 0 to test all samples)

data_folder: None
 
